algoritmo "Dia"
var
 dia:inteiro
inicio
      escreval("Digite o a semana")
      leia(dia)
      escolha dia
      caso 1
      escreva("Domingo")
      caso 2
      escreva("segunda")
      caso 3
      escreva("Terça-feira")
      caso 4
      escreva("Quarta-feira")
      caso 5
      escreva("Quinta-feira")
      caso 6
      escreva("Sexta-feira")
      caso 7
      escreva("Sábado")
      caso 8
      escreva("Nenhuma semana selecionada")
      fimescolha
fimalgoritmo